slides industria
merge-it/2018 pull request #47
Opened 2018-03-29 17:09 UTC by Mte90

aspetta a fare il merge finché non sono di più cosi ti eviti millemila notifiche :-)

2018-04-09 20:03 UTC, claudionaviglio commented
Ciao Daniele, ecco qua il link della mia presentazione.
https://www.dropbox.com/s/ecucmh5xalpolb3/Talk_Merge-it_2018_Naviglio_16_9.pdf?dl=0
Tienimi aggiornato se riesci mandami poi il link dove verranno pubblicate anche quelle dei vari relatori. Grazie, teniamoci in contatto, ciao

Claudio Naviglio

2018-04-10 06:56 UTC, fpietrosanti commented
[GlobaLeaks - MERGE-IT 2018.pdf](https://github.com/merge-it/2018/files/1893147/GlobaLeaks.-.MERGE-IT.2018.pdf)

2018-04-10 09:37 UTC, emilyalbini requested changes
Riuscite a caricare tutti i file PDF direttamente all'interno del repo?

2018-04-10 10:07 UTC, Mte90 commented
Una volta che ho tutte le slide possiamo vedere, al momento mi manca solo un talk :-)

2018-04-10 20:59 UTC, marco55555 commented
Ecco le mie
[Sw_libero_news_180324.pdf](https://github.com/merge-it/2018/files/1896399/Sw_libero_news_180324.pdf)

2018-04-10 21:03 UTC, Mte90 commented
Abbiamo tutti i talk del nostro programma, alcuni sono stati già caricati su github ma non nel repo è un problema?

2018-04-10 21:04 UTC, pietroalbini commented
Preferirei averli tutti nel repo: i talk caricati su GitHub in realtà sono stati allegati alla pull request, quindi non sono presenti nel repository git.

2018-04-10 21:25 UTC, emilyalbini approved these changes
Grazie!

2018-04-10 21:25 UTC, merged